version: "3"
services:
  crow_logger:
    image: crow/crow-qin
    ports:
      - 1840:1840
    environment:
      - CROW_MYSQL_IP="127.0.0.1"
      - CROW_MYSQL_PORT="3306"
      - CROW_MYSQL_DB_NAME="crow"
      - CROW_MYSQL_USER="root"
      - CROW_MYSQL_PASSWORD="1234"
      - CROW_RIDES_IP="127.0.0.1"
      - CROW_RIDES_PORT="6379"
      - CROW_RIDES_DB_NUM=2
      - CROW_RIDES_PASSWORD=
    restart: always
